image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

before_script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - source $CI_PROJECT_DIR/environment

build-main:
  script:
    - /kaniko/executor
      --snapshotMode=redo
      --build-arg login_text="${LOGIN_TEXT}"
      --build-arg collab_text="${COLLAB_TEXT}"
      --build-arg admin_is_sysadmin="${ADMIN_IS_SYSADMIN}"
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination "$CI_REGISTRY_IMAGE"
      --destination "$CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_SLUG"
  only:
    - main

build:
  script:
    - /kaniko/executor
      --snapshotMode=redo
      --build-arg login_text="${LOGIN_TEXT}"
      --build-arg collab_text="${COLLAB_TEXT}"
      --build-arg admin_is_sysadmin="${ADMIN_IS_SYSADMIN}"
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - main
