name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the image
      uses: docker/build-push-action@v3.2.0
      with:
        tags: ghcr.io/lakelink/overleaf-ldap-oauth2:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/lakelink/overleaf-ldap-oauth2:latest
        cache-to: type=inline
